MapColonies/mapproxy-api

openapi3.yaml, package-lock.json, package.json, src/common/exceptions/http/badRequestError.ts, src/common/exceptions/http/httpError.ts, src/common/exceptions/http/internalServerError.ts, src/common/exceptions/http/notFoundError.ts, src/common/middlewares/ErrorHanlder.ts
=> feat: added error handling

openapi3.yaml, src/serverBuilder.ts, tests/integration/resourceName/helpers/requestSender.ts, tests/integration/resourceName/resourceName.spec.ts
=> feat: updated openapi3 swagger

openapi3.yaml, src/common/interfaces.ts, src/common/utils.ts, src/layers/controllers/layersController.ts, src/layers/models/layersManager.ts, src/layers/routes/layersRouterFactory.ts, tests/unit/layers/models/layersManager.spec.ts
| New feature     | ✔                                                                       |
| Breaking change |✖                                                                        |
| Tests added     | ✔                                                                      | …
=> feat: added implementation to reorder mosaic layers

openapi3.yaml, src/layers/controllers/layersController.ts, src/layers/models/layersManager.ts, src/layers/routes/layersRouterFactory.ts, tests/unit/layers/models/layersManager.spec.ts
| Tests added     | ✔                                                                       | …
=> feat: added remove layer implementation

Dockerfile
=> fix: fixed magic number port expose

openapi3.yaml, src/layers/controllers/layersController.ts, src/layers/models/layersManager.ts, src/layers/routes/layersRouterFactory.ts, tests/unit/layers/models/layersManager.spec.ts
| Breaking change |✖                                                                        |
| Tests added     | ✔                                                                       | …
=> feat: added update layer implementation

.prettierignore, src/common/exceptions/http/serviceUnavailableError.ts, src/common/middlewares/ErrorHanlder.ts, src/common/utils.ts, tests/unit/layers/common/utils.spec.ts, tests/unit/layers/models/layersManager.spec.ts, tests/unit/mock/mockContent.yaml, tests/unit/mock/mockInvalidYamlSyntax.yaml
| Tests added     | ✔                                                                        | …
=> test: added utils tests

openapi3.yaml, src/common/interfaces.ts, src/common/utils.ts, src/layers/controllers/layersController.ts, src/layers/models/layersManager.ts, src/layers/routes/layersRouterFactory.ts, src/serverBuilder.ts, tests/unit/layers/common/utils.spec.ts, tests/unit/layers/models/layersManager.spec.ts
| Bug fix         | ✔                                                                      | …
=> fix: fixed operations routes

README.md, config/custom-environment-variables.json, config/default.json, src/common/interfaces.ts
| Documentation   | ✔                                                                        | …
=> chore: updated README file

.github/workflows/release-on-tag-push.yaml, .gitignore, Dockerfile, config/default.json, openapi3.yaml, package-lock.json, package.json
=> fix: snyc issues

README.md, config/custom-environment-variables.json, config/default.json, src/common/interfaces.ts, src/common/providers/s3Provider.ts
| Documentation   | ✔                                                                      | …
=> chore: changed aws envs keys to s3

openapi3.yaml, src/common/cacheProviders/S3Source.ts, src/common/cacheProviders/fsSource.ts, src/common/cacheProviders/gpkgSource.ts, src/common/data/mock/mockLayer.ts, src/common/enums/sourceTypes.ts, src/common/interfaces.ts, src/common/providers/dbProvider.ts, src/layers/models/layersManager.ts, tests/integration/layers/layersManager.spec.ts, tests/unit/layers/models/layersManager.spec.ts, tests/unit/mock/mockLayerNameAlreadyExists.ts, tests/unit/mock/mockLayerNameIsNotExists.ts
| Tests added     | ✔                                                                        | …
=> feat: added fs cache dir support as source

src/common/cacheProviders/S3Source.ts, src/common/cacheProviders/fsSource.ts, src/common/utils.ts, tests/unit/layers/models/layersManager.spec.ts
| Bug fix         | ✔                                                                       |
| Breaking change |✖                                                                        | …
=> chore: added seperator char in the end of directory path

src/common/cacheProviders/S3Source.ts, src/common/cacheProviders/fsSource.ts, src/common/utils.ts
=> chore: adjust tiles path by source cache type

config/custom-environment-variables.json, package-lock.json, package.json
=> feat: fix ssl format and npm audit fix

config/custom-environment-variables.json, config/default.json, src/common/interfaces.ts, src/common/utils.ts, tests/integration/testContainerConfig.ts, tests/unit/layers/models/layersManager.spec.ts
=> fix: fixed tiles path from fs mount directory

openapi3.yaml, src/common/data/mock/mockLayer.ts, src/common/interfaces.ts, src/layers/models/layersManager.ts, tests/integration/layers/layersManager.spec.ts, tests/unit/layers/models/layersManager.spec.ts, tests/unit/mock/mockLayerNameAlreadyExists.ts, tests/unit/mock/mockLayerNameIsNotExists.ts
=> fix: fixed title value

config/custom-environment-variables.json, config/default.json, src/common/providers/dbProvider.ts
=> fix: password ignore

.github/workflows/build_and_push.yaml
=> fix: build and push workflow

helm/templates/configmap.yaml, helm/templates/deployment.yaml, helm/values.yaml
=> chore: adapt cnofig provider key to umbrella

package-lock.json
=> fix: run audit fix

package-lock.json, src/common/exceptions/http/conflictError.ts, src/common/interfaces.ts, src/common/middlewares/ErrorHanlder.ts, src/common/providers/dbProvider.ts, src/common/providers/fSProvider.ts, src/common/providers/s3Provider.ts, src/layers/models/layersManager.ts, tests/integration/layers/layersManager.spec.ts, tests/integration/testContainerConfig.ts, tests/unit/layers/models/layersManager.spec.ts, tests/unit/mock/mockConfigProvider.ts
=> fix: db provider atomic updates

package-lock.json, src/common/interfaces.ts, src/layers/models/layersManager.ts
optimization param per layer cache on creation
| Tests added     | ✖ …
=> feat: adding layer cache param of "minimize_meta_request=true" (MAPCO-2760)

helm/templates/deployment.yaml, helm/values.yaml
| New feature     |✖                                                                        | …
=> fix: internal mount dir for fs storage

helm/templates/deployment.yaml, src/layers/models/layersManager.ts, tests/unit/layers/models/layersManager.spec.ts
| Deprecations    |✖                                                                        |
| Tests added     | ✔                                                                        | …
=> fix: layer name (MAPCO-4005)

config/default.json, helm/templates/configmap.yaml, helm/values.yaml
=> fix: chart configmap condition + default values

.github/workflows/build_and_push.yaml
=> fix: support helm registry auto pushing

helm/templates/_resources.tpl, helm/templates/ingress.yaml, helm/values.yaml
=> chore: auto ingress host

config/default.json, helm/templates/_tplValues.tpl, helm/templates/configmap.yaml, helm/values.yaml, openapi3.yaml, package-lock.json, package.json, src/configs/models/configsManager.ts, src/layers/models/layersManager.ts, tests/unit/configs/models/configsManager.spec.ts, tests/unit/layers/models/layersManager.spec.ts, tests/unit/mock/tracer.ts
=> feat: add tracing (MAPCO-3914)

.github/workflows/build-and-push.yaml
=> chore: added latest github workflow to support push to acr

config/default.json, src/layers/models/layersManager.ts, tests/integration/layers/layersManager.spec.ts, tests/unit/layers/models/layersManager.spec.ts, tests/unit/mock/mockData.ts
| Tests added     | ✔                                                                 | …
=> feat: Grid validation on insert and update (MAPCO-3975)

src/DAL/migration/fullSchema.sql, src/DAL/migration/mapproxy_init.json
| Bug fix         | ✔                                                                       | …
=> fix: add s3 config to globals in init.json file(MAPCO-4504)
